-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 00:59:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FullyMed
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `FullyMed` ;

-- -----------------------------------------------------
-- Schema FullyMed
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FullyMed` DEFAULT CHARACTER SET utf8 ;
USE `FullyMed` ;

-- -----------------------------------------------------
-- Table `FullyMed`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FullyMed`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `conselho_classe` VARCHAR(10) NULL,
  `estado_emissor` VARCHAR(2) NULL,
  `registro_conselho_classe` VARCHAR(15) NULL,
  `email` VARCHAR(45) NOT NULL,
  `user` VARCHAR(15) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `device_token` VARCHAR(255) NULL,
  `status` INT NULL,
  `dt_criacao` DATETIME DEFAULT now(),
  `dt_atualizacao` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FullyMed`.`permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FullyMed`.`permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FullyMed`.`usuario_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FullyMed`.`usuario_permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permissao_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_permissao_permissao_idx` (`permissao_id` ASC),
  INDEX `fk_usuario_permissao_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_usuario_permissao_permissao`
    FOREIGN KEY (`permissao_id`)
    REFERENCES `FullyMed`.`permissao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_permissao_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `FullyMed`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
